export const componentsNames = {
    MAIN: 'main',
    NAVBAR: 'js__navbar',
    SIDEBAR: 'js__sidebar',
    FEED_CONTENT: 'main-page-window',
    LOGIN_FORM: 'login-content',
    REGISTER_FORM: 'registration-content',
    PAGE404: 'page404-block',
    ARTIST_CONTENT: 'js__artist-page-window',
    ARTIST_COVER: 'artist-cover',
    ARTIST_LIKED_SONGS: 'liked-songs',
    ARTIST_TAPE: 'tape',
    ARTIST_LINE_LIST: 'artist-line-list',
    ALBUM_LINE_LIST: 'album-line-list',
    TRACK_LINE_LIST: 'track-line-list',
    USER: 'user',
    PLAYER: 'js__player-main',
    ALBUM: 'js__album',
    TRACK: 'js__track',
    PLAYLIST: 'js__playlist',
    MENU_PLAYLISTS_LIST: 'js__menu-playlists',

    LIBRARY_LIST: 'library-list',
    LIBRARY: 'js__library',
    LIBRARY_TRACKS: 'js__library-tracks',
    TRACK_LIBRARY_LINE_LIST: 'track-library-line-list',
    PLAYLIST_LINE_LIST: 'playlist-line-list',
    PLAYLIST_MODAL_WINDOW: 'modal-overlay',
    LIBRARY_ARTISTS: 'js__library-artists',
    LIBRARY_ALBUMS: 'js__library-albums',
    LIBRARY_PLAYLISTS: 'js__library-playlists',
    SEARCH_LINE: 'SEARCH_LINE',
    SEARCH_CONTENT: 'search-content',
    SEARCH_LIST: 'SEARCH_LIST',

    SIDEBAR_LINK: 'sidebar__link',
    SIDEBAR_ITEM: 'sidebar__item',
};
