name: Frontend Actions

on:
  push:
    branches: [dev/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run buildProduct

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 89.208.199.114
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/frontend/2023_1_Technokaif/dist"
          strip_components: 1
      - name: Deploy static files to server
        uses: appleboy/ssh-action@master
        with:
          host: 89.208.199.114
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cp -r /home/ubuntu/frontend/2023_1_Technokaif/dist/static/* static/ && aws s3 sync ./media/ s3://fluire/media --endpoint-url http://hb.bizmrg.com && aws s3 sync ./static/ s3://fluire/static --endpoint-url http://hb.bizmrg.com
